/**
 * Static Encyclopedia Data
 */
export interface StaticDestination {
  id: string; slug: string; cityAr: string; cityEn?: string; countryAr: string;
  descriptionAr: string; shortSummaryAr: string; travelStyles: string[];
  bestForAr: string[]; popularAreasAr: string[]; topActivitiesAr: string[];
  suggestedDurations: string[]; budgetLevel: string; seasonNotesAr?: string;
}
export interface StaticTemplate {
  id: string; slug: string; titleAr: string; serviceType: string; cityAr?: string;
  summaryAr: string; idealFor: string[]; durationDays?: number; includesAr: string[];
  budgetLevel: string; disclaimersAr: string[];
}
export interface StaticStayGuide {
  id: string; type: string; cityAr: string; titleAr: string; descriptionAr: string;
  featuresAr: string[]; idealFor: string[]; hasPoolHint?: boolean; budgetLevel: string;
}
export const staticDestinations: StaticDestination[] = [
  { id: 'd-riyadh', slug: 'riyadh', cityAr: 'الرياض', cityEn: 'Riyadh', countryAr: 'المملكة العربية السعودية', descriptionAr: 'عاصمة المملكة ونابض قلبها. تجمع بين عبق التاريخ وطابع الحداثة.', shortSummaryAr: 'عاصمة المملكة، قلب سياسي واقتصادي.', travelStyles: ['FAMILY', 'BUSINESS', 'CULTURE', 'LUXURY'], bestForAr: ['العمل', 'الثقافة', 'التسوق', 'المطاعم الفاخرة'], popularAreasAr: ['حي العليا', 'حي الملقا', 'حي النخيل', 'الديرة'], topActivitiesAr: ['برج المملكة', 'رياض بارك', 'متحف الملك سعود', 'وادي حنيفة'], suggestedDurations: ['يومين', '3 أيام', 'أسبوع'], budgetLevel: 'MIXED', seasonNotesAr: 'أفضل وقت من نوفمبر إلى مارس.' },
  { id: 'd-jeddah', slug: 'jeddah', cityAr: 'جدة', cityEn: 'Jeddah', countryAr: 'المملكة العربية السعودية', descriptionAr: 'عروس البحر الأحمر. تشتهر بتراثها البحري وثقافتها المتنوعة.', shortSummaryAr: 'عروس البحر الأحمر، بوابة الحرمين.', travelStyles: ['FAMILY', 'RELIGIOUS', 'CULTURE', 'SHOPPING'], bestForAr: ['القرب من الحرمين', 'التسوق', 'المأكولات البحرية', 'الكورنيش'], popularAreasAr: ['الكورنيش', 'حي الشاطئ', 'حي الروضة', 'حي الحمراء'], topActivitiesAr: ['المشي على الكورنيش', 'نافورة الملك فهد', 'حي مصر', 'جزيرة الفرسان'], suggestedDurations: ['3 أيام', '4 أيام', 'أسبوع'], budgetLevel: 'MIXED', seasonNotesAr: 'معتدلة شتاءً.' },
  { id: 'd-makkah', slug: 'makkah', cityAr: 'مكة المكرمة', cityEn: 'Makkah', countryAr: 'المملكة العربية السعودية', descriptionAr: 'أقدس مدينة في الإسلام. تضم المسجد الحرام والكعبة المشرفة.', shortSummaryAr: 'أقدس مدينة في الإسلام.', travelStyles: ['RELIGIOUS', 'FAMILY'], bestForAr: ['العبادة', 'روحانيات', 'القرب من الحرم'], popularAreasAr: ['المسجد الحرام', 'منى', 'عرفات'], topActivitiesAr: ['الطواف', 'السعي', 'الصلاة في الحرم'], suggestedDurations: ['3 أيام', '5 أيام', 'أسبوع'], budgetLevel: 'MIXED' },
  { id: 'd-madinah', slug: 'madinah', cityAr: 'المدينة المنورة', cityEn: 'Medina', countryAr: 'المملكة العربية السعودية', descriptionAr: 'ثاني أقدس مدينة في الإسلام. تضم المسجد النبوي.', shortSummaryAr: 'ثاني أقدس مدينة.', travelStyles: ['RELIGIOUS', 'FAMILY', 'CULTURE'], bestForAr: ['العبادة', 'روحانيات', 'التاريخ الإسلامي'], popularAreasAr: ['المسجد النبوي', 'جبيل', 'أحد'], topActivitiesAr: ['الصلاة في المسجد النبوي', 'زيارة قباء', 'التجول في جبال أحد'], suggestedDurations: ['3 أيام', '5 أيام', 'أسبوع'], budgetLevel: 'MIXED' },
  { id: 'd-dubai', slug: 'dubai', cityAr: 'دبي', cityEn: 'Dubai', countryAr: 'الإمارات العربية المتحدة', descriptionAr: 'مدينة المستقبل ووجهة السياح الأولى.', shortSummaryAr: 'مدينة المستقبل، تسوق وفعاليات.', travelStyles: ['FAMILY', 'LUXURY', 'SHOPPING', 'BUSINESS', 'ADVENTURE'], bestForAr: ['التسوق', 'الفعاليات', 'العمارة', 'الشواطئ'], popularAreasAr: ['بر دبي', 'ديرة', 'الجميرا', 'دبي مول'], topActivitiesAr: ['التسوق', 'برج خليفة', 'صحراء', 'مرسى دبي', 'جزر النخيل'], suggestedDurations: ['3 أيام', '4 أيام', 'أسبوع'], budgetLevel: 'LUXURY', seasonNotesAr: 'أفضل وقت من نوفمبر إلى مارس.' },
  { id: 'd-abha', slug: 'abha', cityAr: 'أبها', cityEn: 'Abha', countryAr: 'المملكة العربية السعودية', descriptionAr: 'عروس الجبل. تتميز بمناخها البارد الخضري وطبيعتها الساحرة.', shortSummaryAr: 'جبلية باردة، طبيعة خضراء.', travelStyles: ['FAMILY', 'ADVENTURE', 'RELAX', 'CULTURE'], bestForAr: ['الطبيعة', 'المناخ البارد', 'الاسترخاء'], popularAreasAr: ['مدينة أبها', 'رجال ألمع', 'بللجرشي', 'النماص'], topActivitiesAr: ['رجال ألمع', 'السودة', 'التخييم', 'الطبيعة'], suggestedDurations: ['3 أيام', '4 أيام', 'أسبوع'], budgetLevel: 'MID', seasonNotesAr: 'أفضل وقت من مايو إلى سبتمبر.' },
  { id: 'd-alula', slug: 'alula', cityAr: 'العلا', cityEn: 'AlUla', countryAr: 'المملكة العربية السعودية', descriptionAr: 'كنز أثري وطبيعي استثنائي.', shortSummaryAr: 'موقع أثري استثنائي.', travelStyles: ['ADVENTURE', 'CULTURE', 'LUXURY', 'HISTORY'], bestForAr: ['التاريخ', 'الآثار', 'الطبيعة الصحراوية', 'الفخامة'], popularAreasAr: ['مدرج هجر', 'الأوابد', 'وادي成才'], topActivitiesAr: ['جولة أثرية', 'التخييم الصحراوي', 'طيران مروحي'], suggestedDurations: ['3 أيام', '4 أيام', 'أسبوع'], budgetLevel: 'LUXURY', seasonNotesAr: 'معتدلة من أكتوبر إلى مارس.' },
  { id: 'd-istanbul', slug: 'istanbul', cityAr: 'إسطنبول', cityEn: 'Istanbul', countryAr: 'تركيا', descriptionAr: 'مدينة القارتين حيث تلتقي أوروبا بآسيا.', shortSummaryAr: 'تقاطع الحضارات.', travelStyles: ['FAMILY', 'CULTURE', 'SHOPPING', 'RELIGIOUS', 'ADVENTURE'], bestForAr: ['التاريخ', 'المعالم الأثرية', 'التسوق', 'المأكولات'], popularAreasAr: ['الفتح', 'بي أوغلو', 'السلطان أحمد'], topActivitiesAr: ['آيا صوفيا', 'مسجد السلطان أحمد', 'البازار الكبير'], suggestedDurations: ['4 أيام', '5 أيام', 'أسبوع'], budgetLevel: 'MIXED', seasonNotesAr: 'أفضل وقت من أبريل إلى يونيو.' },
  { id: 'd-paris', slug: 'paris', cityAr: 'باريس', cityEn: 'Paris', countryAr: 'فرنسا', descriptionAr: 'عاصمة الأنوار ورومانسية.', shortSummaryAr: 'عاصمة الأنوار.', travelStyles: ['COUPLES', 'CULTURE', 'SHOPPING', 'LUXURY'], bestForAr: ['الرومانسية', 'المتاحف', 'الموضة', 'المطبخ'], popularAreasAr: ['الشانزليزيه', 'مونمارتر', 'اللوفر'], topActivitiesAr: ['برج إيفل', 'اللوفر', 'كاتدرائية نوتردام'], suggestedDurations: ['4 أيام', '5 أيام', 'أسبوع'], budgetLevel: 'LUXURY' },
  { id: 'd-london', slug: 'london', cityAr: 'لندن', cityEn: 'London', countryAr: 'المملكة المتحدة', descriptionAr: 'عاصمة الضباب وواحدة من أهم مدن العالم.', shortSummaryAr: 'عاصمة الضباب.', travelStyles: ['FAMILY', 'CULTURE', 'SHOPPING', 'BUSINESS', 'LUXURY'], bestForAr: ['المتاحف', 'التاريخ', 'الملكية', 'التسوق'], popularAreasAr: ['وستمنستر', 'كنسينغتون', 'مايفير'], topActivitiesAr: ['قلعة لندن', 'قصر باكنغهام', 'المتحف البريطاني'], suggestedDurations: ['4 أيام', '5 أيام', 'أسبوع'], budgetLevel: 'LUXURY' },
  { id: 'd-khobar', slug: 'khobar', cityAr: 'الخبر', cityEn: 'Al-Khobar', countryAr: 'المملكة العربية السعودية', descriptionAr: 'مدينة ساحلية جميلة على الخليج.', shortSummaryAr: 'ساحلية هادئة.', travelStyles: ['FAMILY', 'RELAX', 'BEACH'], bestForAr: ['الإطلالة البحرية', 'المطاعم', 'التسوق'], popularAreasAr: ['كورنيش الخبر', 'السفن مول'], topActivitiesAr: ['المشي على الكورنيش', 'تناول الأسماك الطازجة'], suggestedDurations: ['يوم', 'يومين', '3 أيام'], budgetLevel: 'MID' },
  { id: 'd-dammam', slug: 'dammam', cityAr: 'الدمام', cityEn: 'Dammam', countryAr: 'المملكة العربية السعودية', descriptionAr: 'عاصمة المنطقة الشرقية.', shortSummaryAr: 'عاصمة الشرقية.', travelStyles: ['FAMILY', 'BUSINESS', 'BEACH'], bestForAr: ['الأعمال', 'القرب من الخليج', 'المتاحف'], popularAreasAr: ['الكورنيش', 'جزيرة المرجان'], topActivitiesAr: ['زيارة كورنيش الدمام', 'جزيرة المرجان', 'متحف الدمام'], suggestedDurations: ['يومين', '3 أيام'], budgetLevel: 'MID' },
];
export const staticTemplates: StaticTemplate[] = [
  { id: 't-riyadh-weekend', slug: 'riyadh-weekend', titleAr: 'ويكند في الرياض', serviceType: 'PACKAGE', cityAr: 'الرياض', summaryAr: 'نهاية أسبوع في العاصمة.', idealFor: ['FAMILY', 'BUSINESS', 'SHOPPING'], durationDays: 2, includesAr: ['فنادق 4 نجوم', 'برنامج مقترح'], budgetLevel: 'MID', disclaimersAr: ['مستوى تكلفة تقريبي: متوسط. يتم التحديد بعد المراجعة.'] },
  { id: 't-dubai-family', slug: 'dubai-family', titleAr: 'باقة دبي العائلية', serviceType: 'PACKAGE', cityAr: 'دبي', summaryAr: 'رحلة عائلية إلى دبي.', idealFor: ['FAMILY'], durationDays: 4, includesAr: ['فنادق 4-5 نجوم', 'جولة المدينة', 'برنامج مرن'], budgetLevel: 'LUXURY', disclaimersAr: ['مستوى تكلفة تقريبي: فاخر. يتم التحديد بعد المراجعة.'] },
  { id: 't-abha-mountains', slug: 'abha-mountains', titleAr: 'رحلة أبها الجبلية', serviceType: 'PACKAGE', cityAr: 'أبها', summaryAr: 'استمتع بمناخ أبها البارد.', idealFor: ['FAMILY', 'RELAX', 'ADVENTURE'], durationDays: 3, includesAr: ['فنادق أو منتجعات', 'برنامج مقترح', 'أنشطة طبيعية'], budgetLevel: 'MID', disclaimersAr: ['مستوى تكلفة تقريبي: متوسط. يتم التحديد بعد المراجعة.'] },
  { id: 't-alula-heritage', slug: 'alula-heritage', titleAr: 'رحلة العلا الأثرية', serviceType: 'PACKAGE', cityAr: 'العلا', summaryAr: 'اكتشف إرث العلا التاريخي.', idealFor: ['ADVENTURE', 'CULTURE', 'LUXURY'], durationDays: 3, includesAr: ['فنادق فاخرة', 'جولات أثرية', 'أنشطة استثنائية'], budgetLevel: 'LUXURY', disclaimersAr: ['مستوى تكلفة تقريبي: فاخر. يتم التحديد بعد المراجعة.'] },
  { id: 't-istanbul-shopping', slug: 'istanbul-shopping', titleAr: 'باقة إسطنبول للتسوق', serviceType: 'PACKAGE', cityAr: 'إسطنبول', summaryAr: 'رحلة تسوق في البازارات.', idealFor: ['SHOPPING', 'CULTURE'], durationDays: 4, includesAr: ['فنادق', 'برنامج تسوق', 'جولات ثقافية اختيارية'], budgetLevel: 'MIXED', disclaimersAr: ['مستوى تكلفة تقريبي: مختلط. يتم التحديد بعد المراجعة.'] },
  { id: 't-honeymoon-dubai', slug: 'honeymoon-dubai', titleAr: 'شهر عسل في دبي', serviceType: 'PACKAGE', cityAr: 'دبي', summaryAr: 'رومانسية فاخرة في دبي.', idealFor: ['COUPLES', 'LUXURY'], durationDays: 4, includesAr: ['فنادق 5 نجوم', 'تجارب رومانسية', 'عشاء خاص'], budgetLevel: 'LUXURY', disclaimersAr: ['مستوى تكلفة تقريبي: فاخر. يتم التحديد بعد المراجعة.'] },
];
export const staticStayGuides: StaticStayGuide[] = [
  { id: 's-riyadh-chalet', type: 'CHALET', cityAr: 'الرياض', titleAr: 'شاليهات الرياض العائلية', descriptionAr: 'شاليهات مجهزة للعوائل.', featuresAr: ['مسبح خاص', 'جلسة خارجية', 'مطبخ مجهز', 'مكيفات'], idealFor: ['FAMILY', 'FRIENDS'], hasPoolHint: true, budgetLevel: 'MID' },
  { id: 's-jeddah-chalet', type: 'CHALET', cityAr: 'جدة', titleAr: 'شاليهات جدة الساحلية', descriptionAr: 'شاليهات قريبة من الكورنيش.', featuresAr: ['قرب البحر', 'جلسة خارجية', 'مسبح', 'مطبخ'], idealFor: ['FAMILY', 'COUPLES'], hasPoolHint: true, budgetLevel: 'MID' },
  { id: 's-khobar-chalet', type: 'CHALET', cityAr: 'الخبر', titleAr: 'شاليهات الخبر البحرية', descriptionAr: 'شاليهات هادئة على الخليج.', featuresAr: ['إطلالة بحرية', 'جلسة خارجية', 'مسبح', 'هادئ'], idealFor: ['COUPLES', 'FRIENDS', 'FAMILY'], hasPoolHint: true, budgetLevel: 'MID' },
  { id: 's-abha-chalet', type: 'CHALET', cityAr: 'أبها', titleAr: 'شاليهات أبها الجبلية', descriptionAr: 'أجواء باردة في الجبل.', featuresAr: ['مناخ بارد', 'طبيعة خضراء', 'جلسة خارجية', 'مسبح'], idealFor: ['FAMILY', 'RELAX'], hasPoolHint: true, budgetLevel: 'MID' },
  { id: 's-riyadh-rest', type: 'RESTHOUSE', cityAr: 'الرياض', titleAr: 'استراحات الرياض للشباب', descriptionAr: 'استراحات مناسبة للرحلات الشبابية.', featuresAr: ['اقتصادية', 'مطبخ', 'جلسة', 'قريبة من الخدمات'], idealFor: ['FRIENDS', 'ADVENTURE'], budgetLevel: 'ECONOMY' },
  { id: 's-dammam-rest', type: 'RESTHOUSE', cityAr: 'الدمام', titleAr: 'استراحات الدمام الاقتصادية', descriptionAr: 'استراحات مريحة بأسعار مناسبة.', featuresAr: ['اقتصادية', 'مطبخ مجهز', 'مواقف سيارات'], idealFor: ['FRIENDS', 'FAMILY'], budgetLevel: 'ECONOMY' },
];
